matrix:
  include:
  - language: python
    python:
    - "3.6"

    script:
    - ci/menu-ci.py

  - language: android

addons:
  apt:
    packages:
    - python3-jsonschema
    - python3-pil
    - python3-urllib3
