dist: xenial
addons:
  apt:
    packages:
    - python3-dulwich
    - python3-jsonschema
    - python3-pil
    - python3-urllib3
matrix:
  include:
    - language: python

      script:
        - ci/menu-ci.py

    - language: android
      before_install:
        - yes | sdkmanager "platforms;android-27"
